name: Manual workflow

on:
  workflow_dispatch:

jobs:
  manual-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First manual step
        run: |
          echo "Hello, world"
          echo "Hello Again"