name: Predefined workflow

on:
  workflow_dispatch:

jobs:
  predefined-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: NodeJS version
        run: node -v

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: NodeJS  version
        run: node -v
